---
title: "Working with Git"
---

This section is only relevant if you want to use Git (GitHub or Azure DevOps) for this guide or for your project. If you want to use Git for this project, we recommend creating your own repo with the code.

## What is Git?

Git is a tool that helps track changes to files in a project. It's great for teamwork because it allows everyone to work on the same project without interfering with each other's work. It keeps a history of all changes, so you can see what was changed and go back to previous versions if needed. This makes managing and collaborating on projects much easier and more organized. In DfE, we use GitHub for public facing projects that don't contain sensitive code, and we use Azure DevOps for sensitive projects.

## Guidance and workshops

If you are interested in learning on how to work with Git, you can use the following resources to help you learn:

-   [DfE analyst guide Git tips](https://dfe-analytical-services.github.io/analysts-guide/learning-development/git.html).

-   [Learn about using Azure DevOps](https://dfe-analytical-services.github.io/azure-devops-for-analysis/preface.html)

-   [Avoid revealing sensitive information when working with Git](https://dfe-analytical-services.github.io/analysts-guide/RAP/rap-statistics.html#avoid-revealing-sensitive-information)

-   You can also email [statistics.development\@education.gov.uk](mailto:statistics.development@education.gov.uk) to ask about the Introduction to Git and Azure DevOps technical workshop we run in DfE.
