# Help and contact us {.unnumbered}

## General tips

### Help with general R coding

If you need more help to build your R coding skills, we recommend you try this [Introduction to R course](https://department-for-transport.github.io/intro_R/) that was created by colleagues at DfT.

### Custom functions reference page

If you are using any of the custom functions in this guide and you want more help or information, refer to the [custom functions reference](custom_functions.qmd) page.

### The search bar

You can use the search bar at the side of this guide to type in a keyword about what you're looking for. For example, type **frequency table** and it will show clickable results of where this keyword appears throughout the guide.

## Where do I get the scripts and the functions referenced throughout this guide?

Follow the instructions on the [Introductions](index.qmd) page for [downloading the materials](index.qmd#step-1---download-the-materials) to get the scripts required for this guide.

## Common errors with packages and functions

### Errors with R version

If you have the latest version of R downloaded but RStudio still shows an older one, use [this guide to help you switch to the version of R you need](https://bioinformatics.ccr.cancer.gov/docs/rtools/R%20and%20RStudio/2.6_switching_r_version/).

### Errors that contain `loadNamespace`

If you get error messages with `loadNamespace` in them, it means that you do not have the required package, or the correct version of the package installed.

Please refer to the [renv](setting_up_workspace.qmf#renv) section of this guide and follow the instructions to solve this error.

### Errors that contain `could not find function`

If you get error messages with `could not find function` in them, it means that you have not loaded in the packages and functions required for the code to run.

Please refer to the [Loading in packages and functions](setting_up_workspace.qmf#loading-in-packages-and-functions) section of this guide and follow the instructions to solve this error.

### Errors that contain `object <insert object name> not found`

These errors can be due to either not reading data or not putting column names in quotes.

#### Not reading data in

You are trying to use a function on data that has not been read in. To solve this, make sure you read in the data required for the function.

#### Not quoting column names

You did not use quotes for column names in some functions. It's important to do this because otherwise the functions are looking for objects in the environment with those names instead of using variables in the data set with that name. To solve this, use quoted names for the appropriate functions. Refer to the [custom functions reference](custom_functions.qmd) page for help or to the documentation of the specific function you're using.

### Errors that contain `'\U' used without hex digits in character string`

This error occurs when you attempt to read a file into R and use backslashes ( \\ ) in the file path. Use forward slashes ( / ) in the file path instead.

### How do I know which parts to change in a function to suit my analysis?

The best way to do this is to read the documentation for those functions. You can find documentation for the custom functions in this guide in the [custom functions page](custom_functions.qmd). You can find documentation for other functions by typing the function name and the package it comes from in Google or by typing `??package_name::function()` in the console and the documentation will appear in the Help pane in the right hand side.

### Other errors

If you are getting other errors not mentioned above, we recommend you try the following:

#### Google and Stack Overflow

Copy and paste the error into Google and try to find a solution there. [Stack Overflow](https://stackoverflow.com/) is a site that is good for troubleshooting so if you see results that come up with your error from Stack Overflow, we recommend you look at them first.

#### Documentation

Check the documentation of the function that you're getting an error for. You can either Google the function name to get the documentation or type `??package_name::function_name()` in the console to see the documentation in the Help pane of RStudio.

#### Copilot and ChatGPT

::: callout-warning
**Do NOT enter sensitive information into Copilot, ChatGPT or similar websites or apps.**

**Do NOT take everything that is generated by AI as accurate, as the code can be incorrect. This can have unwanted effects on your analysis.**
:::

If you are stuck and none of the above worked, you can use Copilot and ChatGPT to help you solve the error. You can do this by putting the error message into them and asking them how to solve the error or to write sample code that would not generate this error.

## Contact us

If you are experiencing issues and you need to get in touch with us, please email [Christopher.HANLEY\@education.gov.uk](mailto:Christopher.HANLEY@education.gov.uk).
